In [3]:
import numpy as np
import numpy.linalg as la

In [7]:
x = np.array([[0.681122,-0.039007,12.651911,5.134578],
             [-0.039007,0.186751,-3.195680,-1.171947],
             [12.651911,-3.195680,309.242489,128.774489],
             [5.134578,-1.171947,128.774489,57.853156]])
la.eig(x)

(array([3.64042658e+02, 3.61427101e+00, 5.62601757e-02, 2.50328732e-01]),
 array([[ 0.0375468 ,  0.05102509,  0.68411086,  0.72662164],
        [-0.00934139, -0.04503598, -0.72549171,  0.68669227],
        [ 0.92086582,  0.38518966, -0.05626741, -0.02165742],
        [ 0.38795504, -0.92032447,  0.04988069, -0.00238192]]))

In [9]:
la.eig(x)[0][0] /  sum(la.eig(x)[0])

0.9893444330116254

In [10]:
x = np.array([[1,-0.0109310105,0.871754,0.817954],
             [-0.0109310105,1,-0.420516,-0.356544],
             [0.871754,-0.420516,1,0.962757],
             [0.817954,-0.356544,0.962757,1]])
la.eig(x)

(array([2.88487377, 0.99240744, 0.11167894, 0.01103985]),
 array([[ 5.20604996e-01, -4.13261568e-01, -6.49565725e-01,
          3.69120149e-01],
        [-2.41947739e-01, -9.10198860e-01,  2.76676391e-01,
         -1.90917527e-01],
        [ 5.86563489e-01,  1.42104699e-02,  9.08056568e-04,
         -8.09778063e-01],
        [ 5.71292398e-01, -2.34728521e-02,  7.08176333e-01,
          4.14198385e-01]]))

In [11]:
la.eig(x)[0][0] /  sum(la.eig(x)[0])

0.721218443627569