In [6]:
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
import numpy as np
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import AgglomerativeClustering
import pandas as pd
import os 
from collections import defaultdict
from scipy.cluster.vq import *

In [38]:
my_list = os.listdir('data/HMP_Dataset')
all_arrays = defaultdict(list)
for dirname in my_list:
    if not os.path.isdir('data/HMP_Dataset/' + dirname): continue
    for filename in os.listdir('data/HMP_Dataset/' + dirname):
        array = np.loadtxt('data/HMP_Dataset/' + dirname + os.sep + filename,dtype= 'float')
        all_arrays[dirname].append(array)

data = []
for items in all_arrays.values():
    data.append((np.vstack(items)))
data_all = np.vstack(data)

In [42]:
vector = []
n = 32
k = 64
for i in range(int(len(data_all) / n)):
    vector.append(data_all[i:i+n].reshape(3*n))
    i += n

In [43]:
vector = np.array(vector)

In [45]:
cluster,labels = kmeans(vector,k)

In [15]:
cluster[0]

(96, 96)

In [26]:
array = []
for i in range(int(len(all_arrays['Walk'][0]) / 32)):
    array.append(all_arrays['Walk'][0][i:i+32].reshape(96))
array = np.array(array)


In [35]:
array = np.array(array)
array
vq(array,cluster[0])

(array([33, 33, 33, 33, 33,  5,  5,  5,  5,  5,  5,  5,  5,  5, 26],
       dtype=int32),
 array([35.07764507, 36.27431321, 38.98869203, 42.71545873, 46.97080549,
        48.03229678, 44.62176077, 41.89780255, 40.55785216, 40.38890561,
        41.59318966, 44.53961394, 47.95711957, 51.77204629, 50.11421265]))

In [37]:
vector.shape

(13954, 96)

In [46]:
cluster

array([[27.95967742, 44.97580645, 41.02419355, ..., 12.88709677,
        38.77419355, 34.71774194],
       [11.63181818, 43.51363636, 35.97272727, ..., 14.27272727,
        42.41818182, 35.55      ],
       [ 9.32      , 49.36      , 28.8       , ..., 17.7       ,
        46.26      , 30.34      ],
       ...,
       [15.90697674, 38.14825581, 36.40406977, ..., 10.97965116,
        38.15406977, 36.47965116],
       [12.2       , 36.63214286, 33.24285714, ..., 12.29285714,
        36.83928571, 32.96071429],
       [11.13350785, 34.42408377, 35.43717277, ..., 12.33246073,
        34.5       , 35.66753927]])